### PR TITLE
scs 2.1.2 (redux)

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is a repeat of #13, which I've [tried](https://github.com/bodono/scs-python/issues/22) to encourage upstream, and which has been green (and [pinged](https://github.com/conda-forge/scs-feedstock/pull/13#issuecomment-604280933)) for two weeks. Therefore, I suggest adding myself to the maintainers (which I also do for ecos, osqp, cvxpy; plus some work [here](https://github.com/conda-forge/scs-feedstock/pull/7) and for [cvxopt](https://github.com/conda-forge/cvxopt-feedstock/pulls?q=is%3Apr+author%3Ah-vetinari)).

Closes #13.

### CODE REVIEW

**Comment by h-vetinari** [comment]
Travis didn't start, is currently [under maintenance](https://www.traviscistatus.com/).

**Comment by h-vetinari** [comment]
@conda-forge-admin, please restart ci

**Comment by h-vetinari** [comment]
@scopatz @jakirkham 
#13 has been green (and pinged) for 2 weeks - this is a resend with myself added as a maintainer. :)

**Comment by scopatz** [comment]
Thanks! Please ping @conda-forge/core in the future for these kinds of absentee maintainer requests, though and not me personally :wink:

**Comment by h-vetinari** [comment]
Alright, will do. Thanks!

**Pull request merged**
